### PR TITLE
Add additional languages

### LINKED ISSUE #34: Add support for more languages
I would be nice to have StringForge support turkish and chinese language, or a way to add custom languages.

### PR DESCRIPTION
**Pull request by Freddo3000**
This pull request adds the remaining supported languages to Stringforge, as listed [here](https://community.bistudio.com/wiki/Stringtable.xml).

Languages added:  
* Korean
* Japanese
* Chinese
* Chinese (Simplified)
* Turkish

Fixes #34

### CODE REVIEW

**Review by alexatstariongroup — APPROVED** [review]
Are you able to build without waiting for an official release? I suppose so, right?

**Review by ajvorobiev — APPROVED** [review]

**Comment by Freddo3000** [comment]
Anything more planned or will there be a release going up soon? @ajvorobiev

**Comment by ajvorobiev** [comment]
Wasn't planning either. But might make one with this.

**Comment by Freddo3000** [comment]
Hate to bump, but what is the status on that? Just want to make sure it hasn't simply fallen to the side.

**Pull request merged**
